name: app_ban_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  cupertino_icons: ^1.0.2
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.6
  animated_text_kit: ^4.2.3
  get: ^4.7.2
  flutter_svg: ^2.1.0
  flutter_rating_bar: ^4.0.1
  http: ^1.4.0
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/   
    - assets/imgs/     
    - assets/imgs/theloai/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
